# Generated by Django 5.2.1 on 2025-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_ebook_publishedbook_book_created_at_book_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
