# Generated by Django 5.2.1 on 2025-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_book_created_at_alter_book_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
