# Generated by Django 5.2.1 on 2025-05-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="name",
            new_name="car_name",
        ),
    ]
